mkdir -p videos
mv *.mp4 videos
mv *.wmv videos
mv *.WMV videos
mv *.mov videos
mv *.MOV videos
mv *.asf videos
mv *.mpeg videos
mkdir -p music
mv *.mp3 music
mv *.wav music
mv *.aac music
mkdir -p documents
mv *.doc documents
mv *.docx documents
mv *.ppt documents
mv *.pptx dcocuments
mv *.pdf documents
mv *.docm documents
mv *.xlsx documents
mv *.ppsx documents
mkdir -p compressed
mv *.zip compressed
mv *.gz compressed
mv *.tar compressed
mv *.7z.* compressed
mv *.7z compressed
mkdir -p images
mv *.jpg images
mv *.png images
mv *.gif images
mv *.webp images
mv *.jfif images
mv *.bmp images
mv *.PNG images
mkdir -p logs
mv *.txt logs
mv *.pro logs
mv *.log logs
mv *.dlt logs
mv *.exc logs
mkdir -p software
mv *.exe sodtware
mkdir -p others
mv *.pac others
mv *.url others
mv *.msg others
mv *.vcf others
